CREATE TABLE IF NOT EXISTS `tk_housing_properties` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `apartment_id` INT NULL DEFAULT NULL,
    `doors` JSON NULL DEFAULT NULL,
    `linking_doors` JSON NULL DEFAULT NULL,
    `house_interior` INT NULL DEFAULT NULL,
    `garage_interior` VARCHAR(255) NULL DEFAULT NULL,
    `interior` JSON NULL DEFAULT NULL,
    `yard` JSON NULL DEFAULT NULL,
    `price` BIGINT UNSIGNED NULL DEFAULT NULL,
    `listing_price` BIGINT UNSIGNED NULL DEFAULT NULL,
    `rent` BIGINT UNSIGNED NULL DEFAULT NULL,
    `last_rent_time` BIGINT UNSIGNED NULL DEFAULT NULL,
    `name` VARCHAR(255) NULL DEFAULT NULL,
    `address` VARCHAR(255) NOT NULL,
    `image` VARCHAR(255) NULL DEFAULT NULL,
    `owner` VARCHAR(60) NULL DEFAULT NULL,
    `permissions` JSON NULL DEFAULT NULL,
    `furniture_house` JSON NULL DEFAULT NULL,
    `furniture_garage` JSON NULL DEFAULT NULL,
    `furniture_yard` JSON NULL DEFAULT NULL,
    `vehicles` JSON NULL DEFAULT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;