ALTER TABLE `users`
ADD IF NOT EXISTS `mdt_image` TEXT DEFAULT NULL,
ADD IF NOT EXISTS `mdt_notes` TEXT DEFAULT NULL;

ALTER TABLE `owned_vehicles`
ADD IF NOT EXISTS `mdt_image` TEXT DEFAULT NULL,
ADD IF NOT EXISTS `mdt_notes` TEXT DEFAULT NULL;